import type { Metadata } from 'next'
import './globals.css'
import { HeadBar } from './HeadBar'
import React from 'react'
// eslint-disable-next-line camelcase
import { Josefin_Sans } from 'next/font/google'

const josefin = Josefin_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tagging App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes='32x32'/>
      </head>
      <body className={josefin.className}>
        <div className="size-full max-w-3xl">
          <HeadBar />
          {children}
        </div>
      </body>
    </html>
  )
}
